// import { Inter } from "next/font/google";
//import "../layout";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "home description",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div>{children}</div>;
}
